// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package gpu_mount

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AddGPUResponse_AddGPUResult int32

const (
	AddGPUResponse_Success         AddGPUResponse_AddGPUResult = 0
	AddGPUResponse_InsufficientGPU AddGPUResponse_AddGPUResult = 1
	AddGPUResponse_PodNotFound     AddGPUResponse_AddGPUResult = 2
)

var AddGPUResponse_AddGPUResult_name = map[int32]string{
	0: "Success",
	1: "InsufficientGPU",
	2: "PodNotFound",
}

var AddGPUResponse_AddGPUResult_value = map[string]int32{
	"Success":         0,
	"InsufficientGPU": 1,
	"PodNotFound":     2,
}

func (x AddGPUResponse_AddGPUResult) String() string {
	return proto.EnumName(AddGPUResponse_AddGPUResult_name, int32(x))
}

func (AddGPUResponse_AddGPUResult) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1, 0}
}

type RemoveGPUResponse_RemoveGPUResult int32

const (
	RemoveGPUResponse_Success     RemoveGPUResponse_RemoveGPUResult = 0
	RemoveGPUResponse_GPUBusy     RemoveGPUResponse_RemoveGPUResult = 1
	RemoveGPUResponse_PodNotFound RemoveGPUResponse_RemoveGPUResult = 2
	RemoveGPUResponse_GPUNotFound RemoveGPUResponse_RemoveGPUResult = 4
)

var RemoveGPUResponse_RemoveGPUResult_name = map[int32]string{
	0: "Success",
	1: "GPUBusy",
	2: "PodNotFound",
	4: "GPUNotFound",
}

var RemoveGPUResponse_RemoveGPUResult_value = map[string]int32{
	"Success":     0,
	"GPUBusy":     1,
	"PodNotFound": 2,
	"GPUNotFound": 4,
}

func (x RemoveGPUResponse_RemoveGPUResult) String() string {
	return proto.EnumName(RemoveGPUResponse_RemoveGPUResult_name, int32(x))
}

func (RemoveGPUResponse_RemoveGPUResult) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3, 0}
}

type AddGPURequest struct {
	PodName              string   `protobuf:"bytes,1,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	Namespace            string   `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	GpuNum               int32    `protobuf:"varint,3,opt,name=gpu_num,json=gpuNum,proto3" json:"gpu_num,omitempty"`
	IsEntireMount        bool     `protobuf:"varint,4,opt,name=is_entire_mount,json=isEntireMount,proto3" json:"is_entire_mount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddGPURequest) Reset()         { *m = AddGPURequest{} }
func (m *AddGPURequest) String() string { return proto.CompactTextString(m) }
func (*AddGPURequest) ProtoMessage()    {}
func (*AddGPURequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *AddGPURequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddGPURequest.Unmarshal(m, b)
}
func (m *AddGPURequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddGPURequest.Marshal(b, m, deterministic)
}
func (m *AddGPURequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddGPURequest.Merge(m, src)
}
func (m *AddGPURequest) XXX_Size() int {
	return xxx_messageInfo_AddGPURequest.Size(m)
}
func (m *AddGPURequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddGPURequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddGPURequest proto.InternalMessageInfo

func (m *AddGPURequest) GetPodName() string {
	if m != nil {
		return m.PodName
	}
	return ""
}

func (m *AddGPURequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *AddGPURequest) GetGpuNum() int32 {
	if m != nil {
		return m.GpuNum
	}
	return 0
}

func (m *AddGPURequest) GetIsEntireMount() bool {
	if m != nil {
		return m.IsEntireMount
	}
	return false
}

type AddGPUResponse struct {
	AddGpuResult         AddGPUResponse_AddGPUResult `protobuf:"varint,1,opt,name=add_gpu_result,json=addGpuResult,proto3,enum=gpu_mount.AddGPUResponse_AddGPUResult" json:"add_gpu_result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *AddGPUResponse) Reset()         { *m = AddGPUResponse{} }
func (m *AddGPUResponse) String() string { return proto.CompactTextString(m) }
func (*AddGPUResponse) ProtoMessage()    {}
func (*AddGPUResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *AddGPUResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddGPUResponse.Unmarshal(m, b)
}
func (m *AddGPUResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddGPUResponse.Marshal(b, m, deterministic)
}
func (m *AddGPUResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddGPUResponse.Merge(m, src)
}
func (m *AddGPUResponse) XXX_Size() int {
	return xxx_messageInfo_AddGPUResponse.Size(m)
}
func (m *AddGPUResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddGPUResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddGPUResponse proto.InternalMessageInfo

func (m *AddGPUResponse) GetAddGpuResult() AddGPUResponse_AddGPUResult {
	if m != nil {
		return m.AddGpuResult
	}
	return AddGPUResponse_Success
}

type RemoveGPURequest struct {
	PodName              string   `protobuf:"bytes,1,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	Namespace            string   `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Uuids                []string `protobuf:"bytes,3,rep,name=uuids,proto3" json:"uuids,omitempty"`
	Force                bool     `protobuf:"varint,4,opt,name=force,proto3" json:"force,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveGPURequest) Reset()         { *m = RemoveGPURequest{} }
func (m *RemoveGPURequest) String() string { return proto.CompactTextString(m) }
func (*RemoveGPURequest) ProtoMessage()    {}
func (*RemoveGPURequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}

func (m *RemoveGPURequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveGPURequest.Unmarshal(m, b)
}
func (m *RemoveGPURequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveGPURequest.Marshal(b, m, deterministic)
}
func (m *RemoveGPURequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveGPURequest.Merge(m, src)
}
func (m *RemoveGPURequest) XXX_Size() int {
	return xxx_messageInfo_RemoveGPURequest.Size(m)
}
func (m *RemoveGPURequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveGPURequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveGPURequest proto.InternalMessageInfo

func (m *RemoveGPURequest) GetPodName() string {
	if m != nil {
		return m.PodName
	}
	return ""
}

func (m *RemoveGPURequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *RemoveGPURequest) GetUuids() []string {
	if m != nil {
		return m.Uuids
	}
	return nil
}

func (m *RemoveGPURequest) GetForce() bool {
	if m != nil {
		return m.Force
	}
	return false
}

type RemoveGPUResponse struct {
	RemoveGpuResult      RemoveGPUResponse_RemoveGPUResult `protobuf:"varint,1,opt,name=remove_gpu_result,json=removeGpuResult,proto3,enum=gpu_mount.RemoveGPUResponse_RemoveGPUResult" json:"remove_gpu_result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *RemoveGPUResponse) Reset()         { *m = RemoveGPUResponse{} }
func (m *RemoveGPUResponse) String() string { return proto.CompactTextString(m) }
func (*RemoveGPUResponse) ProtoMessage()    {}
func (*RemoveGPUResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3}
}

func (m *RemoveGPUResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveGPUResponse.Unmarshal(m, b)
}
func (m *RemoveGPUResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveGPUResponse.Marshal(b, m, deterministic)
}
func (m *RemoveGPUResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveGPUResponse.Merge(m, src)
}
func (m *RemoveGPUResponse) XXX_Size() int {
	return xxx_messageInfo_RemoveGPUResponse.Size(m)
}
func (m *RemoveGPUResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveGPUResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveGPUResponse proto.InternalMessageInfo

func (m *RemoveGPUResponse) GetRemoveGpuResult() RemoveGPUResponse_RemoveGPUResult {
	if m != nil {
		return m.RemoveGpuResult
	}
	return RemoveGPUResponse_Success
}

func init() {
	proto.RegisterEnum("gpu_mount.AddGPUResponse_AddGPUResult", AddGPUResponse_AddGPUResult_name, AddGPUResponse_AddGPUResult_value)
	proto.RegisterEnum("gpu_mount.RemoveGPUResponse_RemoveGPUResult", RemoveGPUResponse_RemoveGPUResult_name, RemoveGPUResponse_RemoveGPUResult_value)
	proto.RegisterType((*AddGPURequest)(nil), "gpu_mount.AddGPURequest")
	proto.RegisterType((*AddGPUResponse)(nil), "gpu_mount.AddGPUResponse")
	proto.RegisterType((*RemoveGPURequest)(nil), "gpu_mount.RemoveGPURequest")
	proto.RegisterType((*RemoveGPUResponse)(nil), "gpu_mount.RemoveGPUResponse")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 415 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x93, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x86, 0xb3, 0x4d, 0x1b, 0xd7, 0x93, 0x36, 0x76, 0x17, 0x24, 0x5c, 0xe8, 0xc1, 0xf2, 0xa1,
	0xf2, 0x01, 0xe5, 0x10, 0x1e, 0x00, 0x15, 0x09, 0x0c, 0x12, 0x8d, 0x2c, 0x57, 0x96, 0x38, 0x20,
	0x59, 0xc6, 0x3b, 0xa9, 0x56, 0xaa, 0x77, 0x17, 0xef, 0x6e, 0x11, 0x8f, 0xc0, 0x63, 0xf0, 0x1e,
	0x3c, 0x1c, 0xb2, 0xdd, 0x24, 0x0e, 0x0d, 0x9c, 0x38, 0xce, 0xb7, 0xde, 0x7f, 0xc6, 0xdf, 0xd8,
	0xe0, 0x96, 0x8a, 0xcf, 0x55, 0x23, 0x8d, 0xa4, 0xee, 0xad, 0xb2, 0x45, 0x2d, 0xad, 0x30, 0xd1,
	0x0f, 0x02, 0xa7, 0x57, 0x8c, 0x25, 0x69, 0x9e, 0xe1, 0x57, 0x8b, 0xda, 0xd0, 0x73, 0x38, 0x56,
	0x92, 0x15, 0xa2, 0xac, 0x31, 0x20, 0x21, 0x89, 0xdd, 0xcc, 0x51, 0x92, 0x2d, 0xcb, 0x1a, 0xe9,
	0x05, 0xb8, 0x2d, 0xd6, 0xaa, 0xac, 0x30, 0x38, 0xe8, 0xce, 0xb6, 0x80, 0x3e, 0x03, 0xa7, 0xcd,
	0x15, 0xb6, 0x0e, 0xc6, 0x21, 0x89, 0x8f, 0xb2, 0xc9, 0xad, 0xb2, 0x4b, 0x5b, 0xd3, 0x4b, 0xf0,
	0xb8, 0x2e, 0x50, 0x18, 0xde, 0x60, 0xdf, 0x36, 0x38, 0x0c, 0x49, 0x7c, 0x9c, 0x9d, 0x72, 0xfd,
	0xb6, 0xa3, 0xd7, 0xdd, 0x2c, 0x3f, 0x09, 0xcc, 0xd6, 0xb3, 0x68, 0x25, 0x85, 0x46, 0xfa, 0x11,
	0x66, 0x25, 0x63, 0x45, 0x9b, 0xdb, 0xa0, 0xb6, 0x77, 0xa6, 0x1b, 0x69, 0xb6, 0xb8, 0x9c, 0x6f,
	0x5e, 0x61, 0xbe, 0x7b, 0x65, 0x5b, 0xda, 0x3b, 0x93, 0x9d, 0x94, 0x8c, 0x25, 0xca, 0xf6, 0x55,
	0x74, 0x05, 0x27, 0xc3, 0x53, 0x3a, 0x05, 0xe7, 0xc6, 0x56, 0x15, 0x6a, 0xed, 0x8f, 0xe8, 0x13,
	0xf0, 0x3e, 0x08, 0x6d, 0x57, 0x2b, 0x5e, 0x71, 0x14, 0x26, 0x49, 0x73, 0x9f, 0x50, 0x0f, 0xa6,
	0xa9, 0x64, 0x4b, 0x69, 0xde, 0x49, 0x2b, 0x98, 0x7f, 0x10, 0x7d, 0x03, 0x3f, 0xc3, 0x5a, 0xde,
	0xe3, 0xff, 0x30, 0xf6, 0x14, 0x8e, 0xac, 0xe5, 0x4c, 0x07, 0xe3, 0x70, 0x1c, 0xbb, 0x59, 0x5f,
	0xb4, 0x74, 0x25, 0x9b, 0x0a, 0x1f, 0x24, 0xf5, 0x45, 0xf4, 0x8b, 0xc0, 0xd9, 0xa0, 0xf3, 0x83,
	0x9f, 0x4f, 0x70, 0xd6, 0x74, 0xf0, 0xb1, 0xa2, 0x97, 0x03, 0x45, 0x8f, 0x2e, 0xee, 0x90, 0x56,
	0x94, 0xd7, 0xc7, 0x6c, 0x5d, 0x5d, 0x83, 0xf7, 0xc7, 0x33, 0xbb, 0xba, 0xa6, 0xe0, 0x24, 0x69,
	0xfe, 0xc6, 0xea, 0xef, 0x7b, 0x34, 0xb5, 0x20, 0x49, 0xf3, 0x0d, 0x38, 0x5c, 0xa4, 0xeb, 0xcf,
	0xec, 0x06, 0x9b, 0x7b, 0x5e, 0x21, 0x7d, 0x0d, 0x93, 0x1e, 0xd0, 0x60, 0xcf, 0x2e, 0x3b, 0xb1,
	0xcf, 0xcf, 0xff, 0xba, 0xe5, 0x68, 0xb4, 0xf8, 0x3c, 0xd8, 0xc4, 0x3a, 0xf4, 0x3d, 0xb8, 0x1b,
	0x46, 0x5f, 0xec, 0x17, 0xd0, 0x47, 0x5f, 0xfc, 0xcb, 0x4e, 0x34, 0xfa, 0x32, 0xe9, 0xfe, 0x94,
	0x57, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0xb4, 0xfe, 0x20, 0xcc, 0x36, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AddGPUServiceClient is the client API for AddGPUService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AddGPUServiceClient interface {
	AddGPU(ctx context.Context, in *AddGPURequest, opts ...grpc.CallOption) (*AddGPUResponse, error)
}

type addGPUServiceClient struct {
	cc *grpc.ClientConn
}

func NewAddGPUServiceClient(cc *grpc.ClientConn) AddGPUServiceClient {
	return &addGPUServiceClient{cc}
}

func (c *addGPUServiceClient) AddGPU(ctx context.Context, in *AddGPURequest, opts ...grpc.CallOption) (*AddGPUResponse, error) {
	out := new(AddGPUResponse)
	err := c.cc.Invoke(ctx, "/gpu_mount.AddGPUService/AddGPU", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AddGPUServiceServer is the server API for AddGPUService service.
type AddGPUServiceServer interface {
	AddGPU(context.Context, *AddGPURequest) (*AddGPUResponse, error)
}

// UnimplementedAddGPUServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAddGPUServiceServer struct {
}

func (*UnimplementedAddGPUServiceServer) AddGPU(ctx context.Context, req *AddGPURequest) (*AddGPUResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddGPU not implemented")
}

func RegisterAddGPUServiceServer(s *grpc.Server, srv AddGPUServiceServer) {
	s.RegisterService(&_AddGPUService_serviceDesc, srv)
}

func _AddGPUService_AddGPU_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddGPURequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddGPUServiceServer).AddGPU(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gpu_mount.AddGPUService/AddGPU",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddGPUServiceServer).AddGPU(ctx, req.(*AddGPURequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AddGPUService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gpu_mount.AddGPUService",
	HandlerType: (*AddGPUServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddGPU",
			Handler:    _AddGPUService_AddGPU_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}

// RemoveGPUServiceClient is the client API for RemoveGPUService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RemoveGPUServiceClient interface {
	RemoveGPU(ctx context.Context, in *RemoveGPURequest, opts ...grpc.CallOption) (*RemoveGPUResponse, error)
}

type removeGPUServiceClient struct {
	cc *grpc.ClientConn
}

func NewRemoveGPUServiceClient(cc *grpc.ClientConn) RemoveGPUServiceClient {
	return &removeGPUServiceClient{cc}
}

func (c *removeGPUServiceClient) RemoveGPU(ctx context.Context, in *RemoveGPURequest, opts ...grpc.CallOption) (*RemoveGPUResponse, error) {
	out := new(RemoveGPUResponse)
	err := c.cc.Invoke(ctx, "/gpu_mount.RemoveGPUService/RemoveGPU", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RemoveGPUServiceServer is the server API for RemoveGPUService service.
type RemoveGPUServiceServer interface {
	RemoveGPU(context.Context, *RemoveGPURequest) (*RemoveGPUResponse, error)
}

// UnimplementedRemoveGPUServiceServer can be embedded to have forward compatible implementations.
type UnimplementedRemoveGPUServiceServer struct {
}

func (*UnimplementedRemoveGPUServiceServer) RemoveGPU(ctx context.Context, req *RemoveGPURequest) (*RemoveGPUResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveGPU not implemented")
}

func RegisterRemoveGPUServiceServer(s *grpc.Server, srv RemoveGPUServiceServer) {
	s.RegisterService(&_RemoveGPUService_serviceDesc, srv)
}

func _RemoveGPUService_RemoveGPU_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveGPURequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemoveGPUServiceServer).RemoveGPU(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gpu_mount.RemoveGPUService/RemoveGPU",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemoveGPUServiceServer).RemoveGPU(ctx, req.(*RemoveGPURequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RemoveGPUService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gpu_mount.RemoveGPUService",
	HandlerType: (*RemoveGPUServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RemoveGPU",
			Handler:    _RemoveGPUService_RemoveGPU_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
